version: 2
updates:
  - package-ecosystem: bundler
    directory: /github-pages-site
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "10:00"
    open-pull-requests-limit: 10
  - package-ecosystem: docker
    directory: /.devcontainer
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /.devcontainer
    schedule:
      interval: weekly
