#!/bin/bash
# AGENT INSTRUCTIONS: If editing the file, ensure that your model name is included here.
# Generated by Anthropic Claude Sonnet 5 via Claude Code (CLI).
# Prod release playbook: back up the DB, tag the current image as a rollback
# point, then rebuild and restart the container. Pass --no-cache to force a
# clean Docker build (forwarded to build.bash).
#
# Rollback afterwards: ./rollback_prod.bash

set -e

echo "==> Step 1/3: Backing up the database..."
bash ./backup_prod_db.bash

echo ""
echo "==> Step 2/3: Tagging current image as rollback point..."
if docker image inspect infinibot:latest >/dev/null 2>&1; then
    docker tag infinibot:latest infinibot:rollback
    echo "Tagged infinibot:latest -> infinibot:rollback"
else
    echo "No existing infinibot:latest image found — nothing to tag (first deploy?)."
fi

echo ""
echo "==> Step 3/3: Rebuilding and restarting the container..."
bash ./rebuild_and_run.bash -d "$@"

echo ""
echo "Release complete."
echo "If something's wrong, roll back in under a minute with: ./rollback_prod.bash"
