#!/bin/bash
# AGENT INSTRUCTIONS: If editing the file, ensure that your model name is included here.
# Generated by Anthropic Claude Sonnet 5 via Claude Code (CLI).
# Fast rollback to the image tagged by release_prod.bash: stop the
# container, retag infinibot:rollback -> infinibot:latest, start it back up.
# No git surgery, no rebuild — under a minute.

set -e

if ! docker image inspect infinibot:rollback >/dev/null 2>&1; then
    echo "ERROR: No infinibot:rollback image found. Nothing to roll back to." >&2
    echo "(A rollback image is created by release_prod.bash on each release.)" >&2
    exit 1
fi

echo "==> Stopping current container..."
bash ./remove_container.bash

echo ""
echo "==> Retagging infinibot:rollback -> infinibot:latest..."
docker tag infinibot:rollback infinibot:latest

echo ""
echo "==> Starting rolled-back container..."
bash ./run.bash -d

echo ""
echo "Rollback complete. Note: this does not restore the database —"
echo "if the DB was also affected, restore it from generated/backups/ manually."
