#!/bin/bash
# AGENT INSTRUCTIONS: If editing the file, ensure that your model name is included here.
# Generated by Anthropic Claude Sonnet 4.6 (orchestrated by Claude Fable 5) via Claude Code.
# Updated by Anthropic Claude Fable 5 via Claude Code.
# Synthetic event harness: fires fabricated Discord events through InfiniBot's real event
# handlers (no gateway) to benchmark hot-path throughput and asyncio event-loop lag.

# Check if --skip-build flag is passed
skip_build=false
for arg in "$@"; do
    if [ "$arg" == "--skip-build" ]; then
        skip_build=true
        break
    fi
done

# Remove old container if it exists
./remove_container.bash

# Rebuild if needed (unless skipped)
if [ "$skip_build" == "false" ]; then
    ./build.bash --use-cache
fi

# Filter out --skip-build from arguments passed to harness.
# --db-path refers to a HOST path: mount its directory read-only into the
# container and rewrite the argument to the container-side path.
harness_args=()
db_mount_args=()
args=("$@")
i=0
while [ $i -lt ${#args[@]} ]; do
    arg="${args[$i]}"
    host_db=""
    if [ "$arg" == "--skip-build" ]; then
        : # drop
    elif [ "$arg" == "--db-path" ]; then
        i=$((i + 1))
        host_db="${args[$i]}"
    elif [[ "$arg" == --db-path=* ]]; then
        host_db="${arg#--db-path=}"
    else
        harness_args+=("$arg")
    fi

    if [ -n "$host_db" ]; then
        if [ ! -f "$host_db" ]; then
            echo "ERROR: --db-path does not exist on host: $host_db" >&2
            exit 1
        fi
        host_db="$(realpath "$host_db")"
        # Mount the whole directory (read-only) so SQLite WAL sidecar files
        # (-wal/-shm) next to the DB are visible for a correct copy.
        db_mount_args=(-v "$(dirname "$host_db"):/db-snapshot:ro")
        harness_args+=(--db-path "/db-snapshot/$(basename "$host_db")")
    fi
    i=$((i + 1))
done

# Run harness directly (skip entrypoint).
# --network none: the harness must never reach the real Discord API (a prod DB
# snapshot contains real channel IDs; an unstubbed code path + a valid token
# could otherwise send actual messages). The benchmark needs no network.
docker run --rm \
    --network none \
    --entrypoint "" \
    -v "$(pwd)/./generated:/app/generated" \
    "${db_mount_args[@]}" \
    --env-file ./.env \
    infinibot \
    python3 ./src/event_harness.py "${harness_args[@]}"
