#!/bin/bash
# AGENT INSTRUCTIONS: If editing the file, ensure that your model name is included here.
# Generated by Anthropic Claude Sonnet 4.6 (orchestrated by Claude Fable 5) via Claude Code.
# Synthetic event harness: fires fabricated Discord events through InfiniBot's real event
# handlers (no gateway) to benchmark hot-path throughput and asyncio event-loop lag.

# Check if --skip-build flag is passed
skip_build=false
for arg in "$@"; do
    if [ "$arg" == "--skip-build" ]; then
        skip_build=true
        break
    fi
done

# Remove old container if it exists
./remove_container.bash

# Rebuild if needed (unless skipped)
if [ "$skip_build" == "false" ]; then
    ./build.bash --use-cache
fi

# Filter out --skip-build from arguments passed to harness
harness_args=()
for arg in "$@"; do
    if [ "$arg" != "--skip-build" ]; then
        harness_args+=("$arg")
    fi
done

# Run harness directly (skip entrypoint)
docker run --rm \
    --entrypoint "" \
    -v "$(pwd)/./generated:/app/generated" \
    --env-file ./.env \
    infinibot \
    python3 ./src/event_harness.py "${harness_args[@]}"
