services:
    infinibot:
        image: infinibot
        container_name: infinibot_container
        restart: "on-failure"
        volumes:
            - ../generated:/app/generated
        env_file:
            - ../.env