services:
  infinibot:
    build: .
    container_name: infinibot_container
    restart: always  # Automatically restart if the bot crashes
    volumes:
      - ../generated:/app/generated  # Persistent data storage