title: InfiniBot
description: A powerful, feature-rich Discord bot for your community
author: InfiniBot Team
theme: minima
show_excerpts: true

minima:
  skin: dark
  date_format: "%b %-d, %Y"
  social_links:
    twitter: infinibot
    github: infinibot
    discord: infinibot

header_pages:
  - about.md
  - features.md
  - docs.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
