#!/usr/bin/env python3
# AGENT INSTRUCTIONS: If editing the file, ensure that your model name is included here.
# Generated by Anthropic Claude Sonnet 4.6 (orchestrated by Claude Fable 5) via Claude Code.
# Synthetic event harness: fires fabricated Discord events through InfiniBot's real event
# handlers (no gateway) to benchmark hot-path throughput and asyncio event-loop lag.

"""
Synthetic event harness for InfiniBot.

Fires fabricated Discord events directly through the bot's real event handlers (no gateway
connection) to measure hot-path throughput and event-loop lag.

Usage:
    python3 ./src/event_harness.py [options]

See documentation/event_harness.md for full usage details.
"""

import argparse
import asyncio
import datetime
import logging
import os
import random
import shutil
import statistics
import sys
import time
import traceback
from typing import Any
from unittest.mock import AsyncMock, Mock, patch
from zoneinfo import ZoneInfo

import nextcord
import psutil

# ---------------------------------------------------------------------------
# Environment isolation — MUST happen before any core.bot import.
# Importing db_manager / file_manager / log_manager here is safe because they
# don't construct the bot or read guild-level configs.
# ---------------------------------------------------------------------------
import core.db_manager as db_manager
from config.file_manager import update_base_path as file_manager_update_base_path
from core.log_manager import (
    setup_logging,
    update_base_path as log_manager_update_base_path,
)

HARNESS_BASE = "./generated/harness-files"


def create_harness_environment(db_path: str | None = None) -> None:
    """
    Create an isolated file/database environment for the harness.

    Mirrors tests.py's ``create_environment()`` but under
    ``./generated/harness-files/`` so it never touches real data.

    If *db_path* is provided the DB is pointed at that path instead and
    seeding is skipped by the caller.
    """
    if db_path:
        # Warn loudly — the caller may be pointing at a prod snapshot.
        print(
            "\n"
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n"
            "WARNING: --db-path was supplied.\n"
            f"  DB path : {db_path}\n"
            "  The harness WILL insert message-log rows into this DB.\n"
            "  Run against a COPY, not your production database!\n"
            "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n"
        )
        # Still need config-file paths to exist.
        os.makedirs(f"{HARNESS_BASE}/configure", exist_ok=True)
        os.makedirs(f"{HARNESS_BASE}/logs", exist_ok=True)
        if not os.path.exists(f"{HARNESS_BASE}/configure/default_profane_words.txt"):
            shutil.copy(
                "./defaults/default_profane_words.txt",
                f"{HARNESS_BASE}/configure/default_profane_words.txt",
            )
        db_manager.database_url = f"sqlite:///{db_path}"
    else:
        shutil.rmtree(HARNESS_BASE, ignore_errors=True)
        os.makedirs(f"{HARNESS_BASE}/files", exist_ok=True)
        os.makedirs(f"{HARNESS_BASE}/backups", exist_ok=True)
        os.makedirs(f"{HARNESS_BASE}/configure", exist_ok=True)

        shutil.copy(
            "./defaults/default_profane_words.txt",
            f"{HARNESS_BASE}/configure/default_profane_words.txt",
        )
        shutil.copy(
            "./defaults/default_jokes.json",
            f"{HARNESS_BASE}/files/jokes.json",
        )

        db_manager.database_url = f"sqlite:///{HARNESS_BASE}/files/harness.db"

    db_manager.init_database()
    file_manager_update_base_path(f"{HARNESS_BASE}/configure/")
    log_manager_update_base_path(f"{HARNESS_BASE}/logs/")


# ---------------------------------------------------------------------------
# Fake Discord object factories
# ---------------------------------------------------------------------------


def make_guild(guild_id: int, guild_name: str) -> Mock:
    """Return a Mock that passes ``isinstance(x, nextcord.Guild)``."""
    guild = Mock(spec=nextcord.Guild)
    guild.id = guild_id
    guild.name = guild_name
    guild.chunked = True
    guild.system_channel = None  # prevents join-message path from sending
    guild.me = Mock(spec=nextcord.Member)
    guild.me.guild_permissions = nextcord.Permissions.all()
    # get_role returns None so default_roles loop is a no-op
    guild.get_role = Mock(return_value=None)
    guild.chunk = AsyncMock()
    guild.fetch_members = Mock(return_value=_async_iter([]))
    return guild


def make_channel(channel_id: int, guild: Mock) -> Mock:
    """Return a Mock that passes ``isinstance(x, nextcord.TextChannel)``."""
    channel = Mock(spec=nextcord.TextChannel)
    channel.id = channel_id
    channel.name = f"general-{channel_id}"
    channel.guild = guild
    channel.send = AsyncMock()
    # Raise NotFound so get_message() short-circuits without crashing
    channel.fetch_message = AsyncMock(
        side_effect=nextcord.NotFound(Mock(), "not found")
    )
    channel.permissions_for = Mock(return_value=nextcord.Permissions.all())
    return channel


def make_member(member_id: int, guild: Mock) -> Mock:
    """Return a Mock that passes ``isinstance(x, nextcord.Member)``."""
    member = Mock(spec=nextcord.Member)
    member.id = member_id
    member.name = f"user_{member_id}"
    member.display_name = f"User {member_id}"
    member.mention = f"<@{member_id}>"
    member.nick = None
    member.bot = False
    member.guild = guild
    member.guild_permissions = nextcord.Permissions.none()
    member.roles = []
    member.ban = AsyncMock()
    member.timeout = AsyncMock()
    member.add_roles = AsyncMock()
    return member


def make_message(
    message_id: int,
    guild: Mock,
    channel: Mock,
    author: Mock,
    content: str = "hello world",
) -> Mock:
    """Return a Mock that passes ``isinstance(x, nextcord.Message)``."""
    msg = Mock(spec=nextcord.Message)
    msg.id = message_id
    msg.content = content
    msg.guild = guild
    msg.channel = channel
    msg.author = author
    msg.created_at = datetime.datetime.now(ZoneInfo("UTC"))
    msg.embeds = []
    msg.attachments = []
    return msg


def make_raw_edit_payload(guild_id: int, channel_id: int, message_id: int) -> Mock:
    payload = Mock(spec=nextcord.RawMessageUpdateEvent)
    payload.guild_id = guild_id
    payload.channel_id = channel_id
    payload.message_id = message_id
    payload.cached_message = None  # simulate uncached — forces DB lookup path
    return payload


def make_raw_delete_payload(guild_id: int, channel_id: int, message_id: int) -> Mock:
    payload = Mock(spec=nextcord.RawMessageDeleteEvent)
    payload.guild_id = guild_id
    payload.channel_id = channel_id
    payload.message_id = message_id
    payload.cached_message = None
    return payload


# ---------------------------------------------------------------------------
# Async iterator helper (for guild.fetch_members)
# ---------------------------------------------------------------------------


async def _async_iter(items):
    for item in items:
        yield item


# ---------------------------------------------------------------------------
# Metrics helpers
# ---------------------------------------------------------------------------


def _percentile(data: list[float], pct: float) -> float:
    if not data:
        return 0.0
    sorted_data = sorted(data)
    idx = (len(sorted_data) - 1) * pct / 100
    lo = int(idx)
    hi = lo + 1
    frac = idx - lo
    if hi >= len(sorted_data):
        return sorted_data[lo]
    return sorted_data[lo] * (1 - frac) + sorted_data[hi] * frac


def _fmt(seconds: float) -> str:
    if seconds < 0.001:
        return f"{seconds * 1000:.3f} ms"
    return f"{seconds * 1000:.1f} ms"


# ---------------------------------------------------------------------------
# Event-loop lag watchdog
# ---------------------------------------------------------------------------


class LoopLagWatchdog:
    """Concurrent task that measures asyncio event-loop lag."""

    INTERVAL = 0.05  # 50 ms

    def __init__(self):
        self._lags: list[float] = []
        self._running = False
        self._task: asyncio.Task | None = None

    async def _run(self):
        self._running = True
        while self._running:
            t0 = asyncio.get_event_loop().time()
            await asyncio.sleep(self.INTERVAL)
            elapsed = asyncio.get_event_loop().time() - t0
            self._lags.append(elapsed - self.INTERVAL)

    def start(self):
        self._task = asyncio.ensure_future(self._run())

    async def stop(self):
        self._running = False
        if self._task:
            try:
                await asyncio.wait_for(self._task, timeout=2.0)
            except (asyncio.TimeoutError, asyncio.CancelledError):
                self._task.cancel()

    def report(self) -> dict:
        lags = self._lags
        if not lags:
            return {"count": 0, "mean": 0.0, "p95": 0.0, "max": 0.0}
        return {
            "count": len(lags),
            "mean": statistics.mean(lags),
            "p95": _percentile(lags, 95),
            "max": max(lags),
        }


# ---------------------------------------------------------------------------
# Seeding
# ---------------------------------------------------------------------------


def seed_guilds(guild_ids: list[int], enable_fraction: float) -> None:
    """
    For *enable_fraction* of guilds, enable logging / leveling / moderation
    profiles so the expensive code paths actually execute.
    """
    from config.server import Server

    n_active = max(1, int(len(guild_ids) * enable_fraction))
    active_ids = guild_ids[:n_active]

    logging.info(
        f"Seeding {n_active}/{len(guild_ids)} guilds with active features "
        f"(fraction={enable_fraction:.0%})"
    )

    for gid in active_ids:
        server = Server(gid)
        server.logging_profile.active = True
        server.leveling_profile.active = True
        server.profanity_moderation_profile.active = True
        server.spam_moderation_profile.active = True


# ---------------------------------------------------------------------------
# Main async harness
# ---------------------------------------------------------------------------


async def run_harness(args: argparse.Namespace, guild_ids: list[int]) -> int:
    """
    Run the synthetic event harness.  Returns exit code (0 = success).
    """
    # ------------------------------------------------------------------
    # Lazy import of core.bot — triggers bot construction and all feature
    # module imports. Must happen AFTER env paths are set.
    # ------------------------------------------------------------------
    import core.bot as bot_module
    from core.bot import bot

    # ------------------------------------------------------------------
    # Patch bot methods so fake Discord objects are returned and so that
    # the real gateway / HTTP calls are never made.
    # ------------------------------------------------------------------
    # Build lookup tables keyed by ID
    guilds_by_id: dict[int, Mock] = {}
    channels_by_id: dict[int, Mock] = {}
    members_by_guild: dict[int, list[Mock]] = {}
    channels_by_guild: dict[int, list[Mock]] = {}

    rng = random.Random(args.seed)

    MEMBERS_PER_GUILD = 10
    CHANNELS_PER_GUILD = 3

    for gid in guild_ids:
        guild = make_guild(gid, f"Guild-{gid}")
        guilds_by_id[gid] = guild

        chans = []
        for ci in range(CHANNELS_PER_GUILD):
            cid = gid * 1000 + ci
            ch = make_channel(cid, guild)
            channels_by_id[cid] = ch
            chans.append(ch)
        channels_by_guild[gid] = chans

        members = []
        for mi in range(MEMBERS_PER_GUILD):
            mid = gid * 10000 + mi
            m = make_member(mid, guild)
            members.append(m)
        members_by_guild[gid] = members

    bot.get_channel = lambda cid: channels_by_id.get(cid)
    bot.get_guild = lambda gid: guilds_by_id.get(gid)
    bot.process_commands = AsyncMock()  # exclude library command processing

    # ------------------------------------------------------------------
    # Set up metrics collectors
    # ------------------------------------------------------------------
    latencies: dict[str, list[float]] = {
        "on_message": [],
        "on_raw_message_edit": [],
        "on_raw_message_delete": [],
        "on_member_join": [],
    }
    errors: dict[str, list[str]] = {
        "on_message": [],
        "on_raw_message_edit": [],
        "on_raw_message_delete": [],
        "on_member_join": [],
    }
    unique_tracebacks: list[str] = []

    # Event mix weights (must sum to 1.0)
    EVENT_WEIGHTS = {
        "on_message": 0.80,
        "on_raw_message_edit": 0.10,
        "on_raw_message_delete": 0.05,
        "on_member_join": 0.05,
    }
    event_types = list(EVENT_WEIGHTS.keys())
    event_probs = [EVENT_WEIGHTS[e] for e in event_types]

    n_events = args.events
    proc = psutil.Process()
    rss_start = proc.memory_info().rss

    # ------------------------------------------------------------------
    # Start event-loop lag watchdog
    # ------------------------------------------------------------------
    watchdog = LoopLagWatchdog()
    watchdog.start()

    wall_start = time.perf_counter()
    msg_counter = 0

    # ------------------------------------------------------------------
    # Event dispatch loop
    # ------------------------------------------------------------------
    for i in range(n_events):
        gid = rng.choice(guild_ids)
        guild = guilds_by_id[gid]
        chans = channels_by_guild[gid]
        members = members_by_guild[gid]
        channel = rng.choice(chans)
        author = rng.choice(members)
        message_id = rng.randint(1_000_000, 9_999_999_999_999)

        event_type = rng.choices(event_types, weights=event_probs, k=1)[0]

        try:
            t0 = time.perf_counter()

            if event_type == "on_message":
                msg = make_message(
                    message_id=message_id,
                    guild=guild,
                    channel=channel,
                    author=author,
                    content=f"Hello from synthetic user {i}",
                )
                await bot_module.on_message(msg)

            elif event_type == "on_raw_message_edit":
                payload = make_raw_edit_payload(gid, channel.id, message_id)
                await bot_module.on_raw_message_edit(payload)

            elif event_type == "on_raw_message_delete":
                payload = make_raw_delete_payload(gid, channel.id, message_id)
                await bot_module.on_raw_message_delete(payload)

            elif event_type == "on_member_join":
                member = rng.choice(members)
                await bot_module.on_member_join(member)

            elapsed = time.perf_counter() - t0
            latencies[event_type].append(elapsed)

        except Exception:
            tb = traceback.format_exc()
            errors[event_type].append(tb)
            if len(unique_tracebacks) < 3:
                # Deduplicate by first line of traceback
                first_line = tb.split("\n")[-2] if "\n" in tb else tb
                if not any(first_line in existing for existing in unique_tracebacks):
                    unique_tracebacks.append(tb)

    wall_end = time.perf_counter()
    await watchdog.stop()

    rss_end = proc.memory_info().rss

    # ------------------------------------------------------------------
    # Build and print summary
    # ------------------------------------------------------------------
    wall_time = wall_end - wall_start
    total_errors = sum(len(v) for v in errors.values())
    total_dispatched = n_events - total_errors  # events that completed

    lag_report = watchdog.report()

    print()
    print("=" * 70)
    print("  INFINIBOT SYNTHETIC EVENT HARNESS — RESULTS")
    print("=" * 70)
    print(f"  Events requested  : {n_events:,}")
    print(f"  Events succeeded  : {total_dispatched:,}")
    print(f"  Events errored    : {total_errors:,}")
    print(f"  Wall time         : {wall_time:.3f} s")
    print(f"  Throughput        : {n_events / wall_time:,.1f} events/sec")
    print(f"  Guilds            : {len(guild_ids):,}")
    print(f"  Active features   : {args.enable_features:.0%} of guilds")
    print(f"  RSS start         : {rss_start / 1024**2:.1f} MiB")
    print(f"  RSS end           : {rss_end / 1024**2:.1f} MiB")
    print()
    print("  --- Per-event-type latency (handler wall time) ---")
    print(f"  {'Event':<30} {'N':>6}  {'mean':>9}  {'p50':>9}  {'p95':>9}  {'max':>9}")
    print(f"  {'-' * 30}  {'-' * 6}  {'-' * 9}  {'-' * 9}  {'-' * 9}  {'-' * 9}")
    for etype, lats in latencies.items():
        if not lats:
            print(f"  {etype:<30} {'0':>6}")
            continue
        mean = statistics.mean(lats)
        p50 = _percentile(lats, 50)
        p95 = _percentile(lats, 95)
        mx = max(lats)
        n_err = len(errors[etype])
        suffix = f"  [{n_err} err]" if n_err else ""
        print(
            f"  {etype:<30} {len(lats):>6}  "
            f"{_fmt(mean):>9}  {_fmt(p50):>9}  {_fmt(p95):>9}  {_fmt(mx):>9}"
            f"{suffix}"
        )
    print()
    print("  --- Event-loop lag watchdog (asyncio sleep(0.05) drift) ---")
    print(f"  Ticks sampled     : {lag_report['count']:,}")
    print(f"  Lag mean          : {_fmt(lag_report['mean'])}")
    print(f"  Lag p95           : {_fmt(lag_report['p95'])}")
    print(f"  Lag max           : {_fmt(lag_report['max'])}")
    print()
    if unique_tracebacks:
        print("  --- First unique error tracebacks ---")
        for idx, tb in enumerate(unique_tracebacks, 1):
            print(f"\n  [Traceback {idx}]")
            for line in tb.splitlines():
                print(f"    {line}")
    print("=" * 70)

    error_rate = total_errors / n_events if n_events else 0
    if error_rate > 0.10:
        print(
            f"\n  WARNING: error rate {error_rate:.1%} exceeds 10% — the fakes likely "
            "need fixing. See tracebacks above."
        )
        return 1
    return 0


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="InfiniBot synthetic event harness — benchmarks hot-path throughput"
    )
    p.add_argument(
        "--events",
        type=int,
        default=5000,
        help="Total number of events to dispatch (default: 5000)",
    )
    p.add_argument(
        "--guilds",
        type=int,
        default=200,
        help="Number of synthetic guilds to create (default: 200)",
    )
    p.add_argument(
        "--seed",
        type=int,
        default=42,
        help="RNG seed for reproducible runs (default: 42)",
    )
    p.add_argument(
        "--smoke",
        action="store_true",
        help="Quick sanity run: override --events to 200, --guilds to 10",
    )
    p.add_argument(
        "--enable-features",
        type=float,
        default=0.25,
        dest="enable_features",
        metavar="FRACTION",
        help=(
            "Fraction of guilds that get logging/leveling/moderation enabled "
            "(default: 0.25)"
        ),
    )
    p.add_argument(
        "--db-path",
        type=str,
        default=None,
        dest="db_path",
        metavar="PATH",
        help=(
            "Point the harness at an existing SQLite DB file (e.g. a prod snapshot). "
            "Seeding is skipped; a WARNING is printed because message-log rows will "
            "be inserted."
        ),
    )
    p.add_argument(
        "--log-level",
        type=str,
        default="WARNING",
        choices=["DEBUG", "INFO", "WARNING", "ERROR"],
        help="Logging verbosity (default: WARNING)",
    )
    return p.parse_args()


def main() -> None:
    args = parse_args()

    if args.smoke:
        args.events = 200
        args.guilds = 10
        print("-- smoke mode: events=200, guilds=10 --")

    # Set up isolated environment (must be before core.bot import AND before
    # setup_logging, because create_harness_environment remaps the log path)
    create_harness_environment(db_path=args.db_path)

    # Set up logging (after path remapping so log files go into harness-files/)
    log_level = getattr(logging, args.log_level.upper(), logging.WARNING)
    setup_logging(log_level)

    # Build synthetic guild IDs
    rng = random.Random(args.seed)
    guild_ids = [rng.randint(100_000_000, 999_999_999) for _ in range(args.guilds)]
    # Deduplicate (extremely unlikely to collide but be safe)
    guild_ids = list(dict.fromkeys(guild_ids))[: args.guilds]

    # Seed guild configs BEFORE importing core.bot so the DB records exist
    # when feature_is_active() is called during the run. Skipped with --db-path:
    # an existing DB (e.g. a prod snapshot) must not receive synthetic profile rows.
    if not args.db_path:
        seed_guilds(guild_ids, args.enable_features)

    exit_code = asyncio.run(run_harness(args, guild_ids))
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
