title: InfiniBot
description: A community-driven, open-source, multi-purpose, verified Discord bot to enhance your server experience.
theme: just-the-docs

# Color scheme supports "light" (default) and "dark"
# Implemented custom themes that should be used:
# - custom-light
# - custom-dark
color_scheme: custom-dark

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cypress-exe.github.io/InfiniBot/" # the base hostname & protocol for your site, e.g. http://example.com
repository: cypress-exe/InfiniBot # for github-metadata

permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"


exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  # theme test code
  - fixtures/


back_to_top: true
back_to_top_text: "Back to top"

footer_content: 'InfiniBot is a community-driven, open-source, multi-purpose, verified Discord bot to enhance your server experience.'

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/cypress-exe/infinibot" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: github-pages-site # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# logo: "/assets/images/infinibot-icon.png"
favicon_ico: "/assets/images/icons/icon-circle.ico"

# For copy button on code
enable_copy_code_button: false

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  Add InfiniBot to Your Server: https://discord.com/oauth2/authorize?client_id=991832387015159911&permissions=1374809222364&scope=bot

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# External navigation links
nav_external_links:
  - title: InfiniBot Source Code
    url: https://github.com/cypress-exe/infinibot

# Define callouts
# callouts_level: loud # or quiet
callouts:
  info:
    title: Info
    color: callout-blue
  note:
    title: Note
    color: callout-purple
  tip:
    title: Tip
    color: callout-green
  success:
    title: Success
    color: callout-green
  warning:
    title: Warning
    color: callout-yellow
  danger:
    title: Careful
    color: callout-red

  highlight:
    color: callout-yellow

  titleless-red:
    color: callout-red
  titleless-orange:
    color: callout-orange
  titleless-yellow:
    color: callout-yellow
  titleless-green:
    color: callout-green
  titleless-blue:
    color: callout-blue
  titleless-purple:
    color: callout-purple
  titleless-grey-dk:
    color: callout-grey-dk
  titleless-grey-lt:
    color: callout-grey-lt