source 'https://rubygems.org'

gem "jekyll", "~> 4.4.1" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem "just-the-docs", "0.12.0" # pinned to the current release
# gem "just-the-docs"        # always download the latest release

# Required for Ruby 3.4+
gem "erb"
gem "logger"
gem "ostruct"
gem "csv"
gem "base64"
gem "bigdecimal"
