#!/usr/bin/env -S uv run --script
# AGENT INSTRUCTIONS: If editing the file, ensure that your model name is included here.
# Generated by Anthropic Claude-Opus-5 via Claude Code.
# Generates downscaled twins of the site's demo GIFs and images, driven by
# scaled-assets.yml, for embedding on sites that can't resize images themselves.
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///
"""
Generate downscaled copies of the site's images and demo GIFs.

Some places we link our assets — discordbotlist.com in particular — render a
markdown box with no control over image width, so a 1080px demo GIF arrives at
full size. This script reads ``scaled-assets.yml`` and writes a smaller twin of
each listed asset into a ``small/`` directory beside it, giving those sites a
URL to point at.

Work is skipped when it isn't needed. Each output is recorded in
``.scaled-state.json`` against the SHA-256 of its source and the settings used
to build it; an output is rebuilt only when one of those changes. The check is
content-based rather than mtime-based on purpose: git doesn't preserve mtimes,
so on a fresh CI checkout every file looks equally new and mtime comparison
would either rebuild all ~100MB of GIFs on every run or none of them ever.

Usage::

    uv run scale_assets.py            # build whatever is stale
    uv run scale_assets.py --force    # rebuild everything
    uv run scale_assets.py --check    # exit 1 if anything is stale, build nothing

Requires ``ffmpeg`` and ``ffprobe`` on PATH.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

SITE_ROOT = Path(__file__).resolve().parent
MANIFEST_FILE = SITE_ROOT / "scaled-assets.yml"

# Deliberately outside assets/: the workflow commits this file, and anything it
# commits under assets/ would re-match the workflow's own path filter.
STATE_FILE = SITE_ROOT / ".scaled-state.json"

# Bump this when the encoder settings below change. It's part of every
# fingerprint, so raising it invalidates and rebuilds every output.
PIPELINE_VERSION = 1

ANIMATED_SUFFIXES = {".gif"}
STILL_SUFFIXES = {".png", ".jpg", ".jpeg", ".webp"}


class ManifestError(Exception):
    """The manifest is malformed or points at something that isn't there."""


@dataclass(frozen=True)
class Asset:
    """One entry from the manifest, resolved against the site root."""

    src: Path  # relative to SITE_ROOT
    width: int
    fps: int | None

    @property
    def src_path(self) -> Path:
        return SITE_ROOT / self.src

    def out_path(self, output_dir: str) -> Path:
        return self.src_path.parent / output_dir / self.src.name

    def out_key(self, output_dir: str) -> str:
        """Stable, platform-independent key for the state file."""
        return self.out_path(output_dir).relative_to(SITE_ROOT).as_posix()


def load_manifest(path: Path = MANIFEST_FILE) -> tuple[str, list[Asset]]:
    """Parse and validate the manifest, returning ``(output_dir, assets)``.

    Every problem here is a typo someone can fix, so they're raised with the
    offending value rather than left to surface as a confusing ffmpeg error.
    """
    if not path.is_file():
        raise ManifestError(f"manifest not found: {path}")

    raw = yaml.safe_load(path.read_text()) or {}
    if not isinstance(raw, dict):
        raise ManifestError(f"{path.name}: expected a mapping at the top level")

    output_dir = raw.get("output_dir", "small")
    if not isinstance(output_dir, str) or not output_dir or "/" in output_dir:
        raise ManifestError(
            f"{path.name}: output_dir must be a single directory name, got {output_dir!r}"
        )

    entries = raw.get("assets")
    if not isinstance(entries, list) or not entries:
        raise ManifestError(f"{path.name}: 'assets' must be a non-empty list")

    assets: list[Asset] = []
    seen: set[Path] = set()
    for index, entry in enumerate(entries):
        where = f"{path.name}: assets[{index}]"
        if not isinstance(entry, dict):
            raise ManifestError(f"{where}: expected a mapping, got {type(entry).__name__}")

        src_value = entry.get("src")
        if not isinstance(src_value, str) or not src_value:
            raise ManifestError(f"{where}: 'src' must be a non-empty string")

        src = Path(src_value)
        if src.is_absolute() or ".." in src.parts:
            raise ManifestError(f"{where}: 'src' must be a relative path inside the site, got {src_value!r}")
        if src in seen:
            raise ManifestError(f"{where}: duplicate src {src_value!r}")
        seen.add(src)

        suffix = src.suffix.lower()
        if suffix not in ANIMATED_SUFFIXES | STILL_SUFFIXES:
            raise ManifestError(f"{where}: unsupported file type {suffix!r} for {src_value!r}")

        width = entry.get("width")
        if not isinstance(width, int) or isinstance(width, bool) or width <= 0:
            raise ManifestError(f"{where}: 'width' must be a positive integer, got {width!r}")

        fps = entry.get("fps")
        if fps is not None:
            if not isinstance(fps, int) or isinstance(fps, bool) or fps <= 0:
                raise ManifestError(f"{where}: 'fps' must be a positive integer, got {fps!r}")
            if suffix not in ANIMATED_SUFFIXES:
                raise ManifestError(f"{where}: 'fps' is only meaningful for GIFs, not {suffix!r}")

        assets.append(Asset(src=src, width=width, fps=fps))

    return output_dir, assets


def require_tools() -> None:
    missing = [tool for tool in ("ffmpeg", "ffprobe") if shutil.which(tool) is None]
    if missing:
        raise SystemExit(
            f"error: {', '.join(missing)} not found on PATH. Install ffmpeg and try again."
        )


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def source_width(path: Path) -> int:
    result = subprocess.run(
        [
            "ffprobe", "-v", "error",
            "-select_streams", "v:0",
            "-show_entries", "stream=width",
            "-of", "default=noprint_wrappers=1:nokey=1",
            str(path),
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    return int(result.stdout.strip().splitlines()[0])


def fingerprint(asset: Asset, src_digest: str) -> dict:
    """What the output was built from. Any change here means a rebuild."""
    return {
        "src": asset.src.as_posix(),
        "src_sha256": src_digest,
        "width": asset.width,
        "fps": asset.fps,
        "pipeline": PIPELINE_VERSION,
    }


def encode_gif(src: Path, dest: Path, width: int, fps: int | None) -> None:
    """Downscale a GIF, regenerating its palette.

    A GIF carries at most 256 colors, and those colors were chosen for the
    source resolution. Resizing without rebuilding the palette leaves the
    encoder approximating new intermediate pixels from the old table, which is
    what makes naively-resized GIFs look muddy.

    ``stats_mode=diff`` weights the palette toward the parts of the frame that
    actually move, which is most of the value on a screen recording where a
    static chrome dominates the pixel count. Dithering is off: these demos are
    flat UI, where dithering adds visible noise, costs bytes, and buys nothing.
    """
    fps_filter = f"fps={fps}," if fps else ""
    filtergraph = (
        f"[0:v] {fps_filter}scale={width}:-1:flags=lanczos,split [a][b];"
        f"[a] palettegen=stats_mode=diff [p];"
        f"[b][p] paletteuse=dither=none:diff_mode=rectangle"
    )
    subprocess.run(
        ["ffmpeg", "-v", "error", "-y", "-i", str(src), "-filter_complex", filtergraph, str(dest)],
        check=True,
    )


def encode_still(src: Path, dest: Path, width: int) -> None:
    subprocess.run(
        [
            "ffmpeg", "-v", "error", "-y",
            "-i", str(src),
            "-vf", f"scale={width}:-1:flags=lanczos",
            "-frames:v", "1",
            str(dest),
        ],
        check=True,
    )


def build(asset: Asset, dest: Path) -> str:
    """Produce ``dest`` from ``asset``. Returns a short note about what was done."""
    dest.parent.mkdir(parents=True, exist_ok=True)

    if source_width(asset.src_path) <= asset.width:
        # Upscaling would only add bytes and blur. Copying keeps the URL shape
        # consistent so callers don't need to special-case already-small assets.
        shutil.copyfile(asset.src_path, dest)
        return "copied (source is already at or below the target width)"

    if asset.src.suffix.lower() in ANIMATED_SUFFIXES:
        encode_gif(asset.src_path, dest, asset.width, asset.fps)
    else:
        encode_still(asset.src_path, dest, asset.width)
    return f"{dest.stat().st_size / 1_000_000:.1f} MB"


def prune_orphans(state: dict, fresh_state: dict) -> list[str]:
    """Delete outputs whose manifest entry has gone away.

    Only files recorded in the previous state are touched, so this can never
    remove something the script didn't create.
    """
    removed = []
    for key in sorted(set(state) - set(fresh_state)):
        path = SITE_ROOT / key
        if path.is_file():
            path.unlink()
            removed.append(key)
    return removed


def load_state() -> dict:
    if not STATE_FILE.is_file():
        return {}
    try:
        return json.loads(STATE_FILE.read_text())
    except json.JSONDecodeError:
        # A corrupt state file should cost a rebuild, not a crash.
        return {}


def save_state(state: dict) -> None:
    STATE_FILE.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    parser.add_argument("--force", action="store_true", help="rebuild every asset")
    parser.add_argument(
        "--check",
        action="store_true",
        help="report stale outputs and exit 1 without building anything",
    )
    args = parser.parse_args(argv)

    try:
        output_dir, assets = load_manifest()
    except ManifestError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    missing_sources = [a.src.as_posix() for a in assets if not a.src_path.is_file()]
    if missing_sources:
        print("error: manifest lists sources that don't exist:", file=sys.stderr)
        for src in missing_sources:
            print(f"  {src}", file=sys.stderr)
        return 2

    if not args.check:
        require_tools()

    state = load_state()
    fresh_state: dict = {}
    stale: list[Asset] = []

    for asset in assets:
        key = asset.out_key(output_dir)
        wanted = fingerprint(asset, sha256_of(asset.src_path))
        fresh_state[key] = wanted
        if args.force or state.get(key) != wanted or not asset.out_path(output_dir).is_file():
            stale.append(asset)

    if args.check:
        if stale:
            print("Stale scaled assets (run `uv run scale_assets.py`):")
            for asset in stale:
                print(f"  {asset.out_key(output_dir)}")
            return 1
        print(f"All {len(assets)} scaled assets are up to date.")
        return 0

    for key in prune_orphans(state, fresh_state):
        print(f"Removed {key} (no longer in the manifest)")

    if not stale:
        print(f"All {len(assets)} scaled assets are up to date.")
        # Still rewrite state: it may be absent or reformatted even when every
        # output is present and correct.
        save_state(fresh_state)
        return 0

    print(f"Rebuilding {len(stale)} of {len(assets)} scaled assets...")
    for asset in stale:
        dest = asset.out_path(output_dir)
        print(f"  {asset.src.as_posix()} -> {asset.out_key(output_dir)} (width {asset.width})", flush=True)
        try:
            note = build(asset, dest)
        except subprocess.CalledProcessError as error:
            print(f"error: ffmpeg failed on {asset.src.as_posix()} ({error})", file=sys.stderr)
            return 1
        print(f"    {note}")

    save_state(fresh_state)
    print("Done.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
